/** Generado desde Google Sheets (Actividades). No editar a mano; ejecute `node scripts/generate-kyb-opciones.mjs`. */
export const ACTIVIDADES_KYB_OPCIONES = [
  "Actividad bancaria",
  "Actividad internacional off shore",
  "Actividad pecuaria - ganado: bovino, equino, ovino (ovejas)",
  "Actividades como agricultura, ganadería, industria, comercio, comunicaciones",
  "Actividades cooperativas de ahorro y crédito",
  "Actividades de casas de cambio y remesas informales",
  "Actividades de casinos y juegos de azar online",
  "Actividades de comercio de piezas para maquinaria pesada",
  "Actividades de comercio de piezas y repuestos para vehículos de lujo",
  "Actividades de comercio de productos agrícolas orgánicos de alto valor",
  "Actividades de comercio de productos importados de lujo",
  "Actividades de comercio de productos tecnológicos avanzados",
  "Actividades de comercio de vehículos de alta gama",
  "Actividades de comercio y distribución de productos electrónicos",
  "Actividades de crowdfunding y financiación colectiva",
  "Actividades de cultivo y exportación de productos forestales valiosos",
  "Actividades de extracción y comercialización de minerales preciosos",
  "Actividades de importación y exportación de vehículos usados",
  "Actividades de investigación y desarrollo en biotecnología financiera",
  "Actividades de loterías y apuestas deportivas",
  "Actividades de manufactura de productos farmacéuticos controlados",
  "Actividades de minería de criptomonedas",
  "Actividades de ocio, cultura y espectáculo",
  "Actividades de producción audiovisual para publicidad y marketing",
  "Actividades de producción y comercialización de cosméticos de lujo",
  "Actividades de producción y exportación de productos pesqueros de alto valor",
  "Actividades de producción y venta de alimentos orgánicos de alto valor",
  "Actividades de producción y venta de bebidas alcohólicas premium",
  "Actividades de producción y venta de energía renovable a gran escala",
  "Actividades de producción y venta de productos de tabaco regulados",
  "Actividades de transporte aéreo de carga especial",
  "Actividades de transporte marítimo de carga valiosa",
  "Actividades de transporte terrestre para mercancías valiosas",
  "Actividades de transporte y logística para productos farmacéuticos",
  "Actividades farmaceuticas",
  "Administración del dinero, valores, cuentas bancarias, ahorros u otros activos",
  "Aerea, fluvial, maritima y terrestre",
  "Aeronáutica comercial",
  "Agencias de seguridad (física)",
  "Agencias de viaje o empresas turísticas",
  "Agricultura hidropónica",
  "Agricultura orgánica certificada",
  "Agricultura y productor pecuario",
  "Alimentos y bebidas no alcohólicas, sea su producción, distribución o venta",
  "Almacenes por departamentos",
  "Alquiler de maquinaria pesada",
  "Alquiler de vehículos",
  "Ama de casa",
  "Animación y efectos digitales",
  "Aplicaciones móviles y desarrollo software",
  "Armas incluyendo militares fabricación, venta, distribución",
  "Artesanías y productos artesanales",
  "Artículos de cuero, sea su elaboración, distribución o venta",
  "Artículos y equipos para oficina, fabricación, venta o distribución",
  "Asesoría ambiental y gestión de residuos",
  "Asesoría en comercio exterior",
  "Asesoría financiera y planificación patrimonial",
  "Auditoría ambiental",
  "Automatización industrial",
  "Autos, equipo pesado, equipo rodante, nuevo o usado",
  "Avicultor",
  "Avicultura orgánica",
  "Banca privada",
  "Bebidas alcohólicas, alcohol etílico, sea elaboración, distribución o venta",
  "Bebidas no alcohólicas, sea elaboración, distribución o venta",
  "Biotecnología agrícola",
  "Bolsas y casa de valores, forex y actividades relacionadas",
  "Café y cultivo de cacao",
  "Call centers para soporte técnico",
  "Capacitación y formación profesional",
  "Carpintería y ebanistería",
  "Casa de cambio y entidades de transferencias (remesas)",
  "Casa de empeño",
  "Casas de cambio, remesadoras de dinero, paradores de cheques, casas de empeño",
  "Casinos, casa de bingo, loteria y otros proveedores de servicios de juego",
  "Catering y servicios de banquetes",
  "Caucho, plástico, foam y similares, su fabricación, venta y distribución",
  "Centro de datos y hosting",
  "Centro de llamadas",
  "Centros de atención para la salud (de cualquier tipo)",
  "Centros de cobros de servicios para terceros",
  "Centros de rehabilitación y terapias alternativas",
  "Centros educativos de cualquier tipo y nivel",
  "Cinematografía y producción audiovisual",
  "Comercialización de productos químicos industriales",
  "Comercio de aeronaves privadas",
  "Comercio de antiguedades, compraventa de arte y galerias",
  "Comercio de armas y municiones no reguladas",
  "Comercio de bicicletas y accesorios",
  "Comercio de criptomonedas y activos digitales",
  "Comercio de joyas finas y piedras preciosas",
  "Comercio de materiales de construcción",
  "Comercio de obras de arte",
  "Comercio de productos de tecnología avanzada",
  "Comercio de productos derivados del petróleo y gas incluye repuestos",
  "Comercio de productos electrónicos de alto valor",
  "Comercio electrónico (e-commerce)",
  "Comercio internacional de productos agrícolas de alto valor",
  "Comercio justo y sostenible",
  "Comida rápida y food trucks",
  "Compañías de importación y exportación",
  "Compra y venta de vehículos usados",
  "Comunicaciones y telecomunicaciones",
  "Construcción / promoción de proyectos inmobiliario",
  "Consultoría en energía renovable",
  "Consultoría en gestión de proyectos",
  "Consultoría en seguridad informática",
  "Contribuciones, creación, operación, compra y ventas de entidades jurídicas",
  "Cooperativas agrícolas",
  "Corredor de Seguros",
  "Corredores de seguros y actividades conexas",
  "Creación de contenido digital y marketing digital",
  "Cría y comercialización de abejas y miel",
  "Cultivo de hongos comestibles",
  "Cultivo de plantas medicinales",
  "Cultivo y comercialización de flores",
  "Cursos y talleres online",
  "Decoración de interiores",
  "Discotecas, salas para bailes, bares, cantinas",
  "Diseño gráfico y multimedia",
  "Diseño industrial",
  "Diseño web y experiencia de usuario (UX/UI)",
  "Distribución de equipos médicos",
  "Distribución de productos orgánicos",
  "Educación ambiental",
  "Electricidad, gas, vapor, agua caliente, telefonía y otros servicios públicos",
  "Emisores o procesadores de tarjetas de débito, crédito, pregadas",
  "Empresas comerciales con transacciones en efectivo",
  "Empresas comerciales e industriales ordinarias",
  "Empresas de reciclaje",
  "Empresas de venta de artículos defensivos, explosivos, pirotecnia y accesorios",
  "Empresas financieras sin supervisión o supervisión con carencias",
  "Energía eólica",
  "Energía solar y fotovoltaica",
  "Entrenamiento deportivo y fitness",
  "Entretenimiento para adultos, pornografía, casa de cita, prostíbulo",
  "Estudios de arquitectura",
  "Exportación e importación de bienes de lujo",
  "Exportación, explotación y comercialización piedras y metales preciosos",
  "Extracción y comercialización de minerales, incluye venta y distribución",
  "Extracción, distribución o venta de petróleo derivados o relacionadas",
  "Fabricación de juguetes",
  "Fabricación de muebles",
  "Fabricación de utensilios de cocina",
  "Fabricación textil ecológica",
  "Fabricación y distribución de productos de limpieza",
  "Fabricación y venta de cosméticos naturales",
  "Fabricación y venta de productos biodegradables",
  "Fabricación y venta de velas artesanales",
  "Fabricante de prendas",
  "Fabricantes de instrumentos musicales",
  "Fabricantes de productos para mascotas",
  "Farmacias",
  "Ferretería",
  "Financiación colectiva: suscripción, plataformas o crowdfunding",
  "Financieras supervisadas",
  "Finanzas verdes y microfinanzas",
  "Firmas que ofrecen servicios de contabilidad (pública autorizada) y auditoría",
  "Firmas que ofrecen servicios legales o jurídicos",
  "Fotografía profesional",
  "Gasolineras",
  "Gestión de eventos y congresos",
  "Gestión de residuos electrónicos",
  "Gestor (a) de clientes o que actúa en nombre de estos",
  "Gimnasios y centros deportivos",
  "Granjas piscícolas, actividades de servicios",
  "Hoteles, hostales, pensiones, cabañas",
  "Importación y exportación",
  "Industria audiovisual y producción de videos",
  "Industria cosmética",
  "Industria del juego digital",
  "Industria del reciclaje de plásticos",
  "Industria editorial y publicación de libros",
  "Industria farmacéutica natural",
  "Industria fotovoltaica",
  "Ingeniería ambiental",
  "Ingeniería civil y obras públicas",
  "Ingeniería de software",
  "Instalación y mantenimiento de paneles solares",
  "Instalación y mantenimiento de sistemas de seguridad",
  "Jardinería y paisajismo",
  "Joyería o comercialización de metales y piedras preciosas, contratos a futuro",
  "Laboratorios",
  "Laboratorios de análisis clínicos",
  "Laboratorios de investigación científica",
  "Lavanderías industriales",
  "Logística y almacenamiento",
  "Manufactura de productos deportivos",
  "Manufactura de productos electrónicos",
  "Marketing digital y publicidad online",
  "Medicina alternativa y terapias naturales",
  "Medios de comunicación digitales",
  "Microcervecerías artesanales",
  "Minerales de uranio y torio, sea extracción, distribución o venta",
  "Minería responsable y sostenible",
  "Minisúper, supermercados e hipermercados",
  "Museos y centros culturales",
  "Música y producción musical",
  "Nanotecnología",
  "Naves (marítimas), aeronaves, nuevo o usado",
  "Negocios como (restaurantes, negocios minoristas, estacionamientos)",
  "Negocios de impresión 3D",
  "Oficinas que ofrecen servicios de notaría o de escribanos",
  "Operaciones con contratos de futuros y derivados financieros",
  "Operaciones de cambio de moneda",
  "Operaciones de financiación comercial con características inusuales de precios",
  "Operadores turísticos ecológicos",
  "Órdenes de dinero/pago",
  "Organización de bodas y eventos sociales",
  "Organización de ferias y exposiciones",
  "Papel y otros derivados de éste, su fabricación, venta o distribución",
  "Pesca, explotación de criaderos de peces",
  "Producción agrícola en invernaderos",
  "Producción audiovisual para redes sociales",
  "Producción de energías limpias",
  "Producción de productos orgánicos para bebés",
  "Productos preparados para el consumo humano y buhoneria",
  "Promoción artística y deportiva",
  "Proveedores de servicios de transferencia de valores monetario (MVTS)",
  "Relacionadas con la pesca, sea producción, distribución o venta",
  "Repuestos o refacciones de autos, equipo rodante, naviero o aéreo",
  "Restaurantes",
  "Sector inmobiliario y de construcción compra y venta de bienes inmobiliarios",
  "Servicios de administración de activos digitales",
  "Servicios de administración de plataformas de inversión digital",
  "Servicios de agentes de bolsa y corretaje financiero",
  "Servicios de agentes de seguros de vida y salud",
  "Servicios de agentes residentes y notariales",
  "Servicios de almacenamiento y custodia de bienes valiosos",
  "Servicios de asesoría financiera offshore",
  "Servicios de auditoría financiera para clientes de alto riesgo",
  "Servicios de auditoría interna para empresas de alto riesgo",
  "Servicios de banca privada",
  "Servicios de cambio de divisas en mercados no regulados",
  "Servicios de comercio electrónico transfronterizo",
  "Servicios de consultoría en cumplimiento regulatorio financiero",
  "Servicios de consultoría en prevención de lavado de activos",
  "Servicios de consultoría para estructuras corporativas complejas",
  "Servicios de consultoría para mercados financieros emergentes",
  "Servicios de consultoría para operaciones de fusiones y adquisiciones",
  "Servicios de contabilidad para empresas offshore",
  "Servicios de corredores de seguros especializados",
  "Servicios de corretaje en mercado de metales preciosos",
  "Servicios de corretaje en mercado de seguros especializados",
  "Servicios de desarrollo y gestión de plataformas blockchain",
  "Servicios de desarrollo y gestión de software financiero",
  "Servicios de factoring y leasing financiero",
  "Servicios de financiamiento para proyectos de infraestructura",
  "Servicios de gestión de fondos de inversión privada",
  "Servicios de gestión de pagos internacionales para comercio electrónico",
  "Servicios de gestión de patrimonio para clientes de alto patrimonio",
  "Servicios de gestión de riesgos financieros para empresas grandes",
  "Servicios de gestión y administración de fondos filantrópicos",
  "Servicios de importación y exportación de productos médicos y quirúrgicos",
  "Servicios de inversión en arte y coleccionables",
  "Servicios de leasing para aeronaves y embarcaciones privadas",
  "Servicios de logística para mercancías sensibles o de alto valor",
  "Servicios de mantenimiento industrial",
  "Servicios de mantenimiento y reparación de embarcaciones privadas",
  "Servicios de notaría para operaciones de bienes raíces de alto valor",
  "Servicios de organización de eventos de alto valor económico",
  "Servicios de pago electrónico y billeteras digitales",
  "Servicios de plataformas de apuestas en línea",
  "Servicios de préstamos no bancarios y financiamiento alternativo",
  "Servicios de procesamiento de pagos para comercio electrónico",
  "Servicios de procesamiento de tarjetas de crédito y débito",
  "Servicios de reparación y mantenimiento de aeronaves privadas",
  "Servicios de soporte técnico y mantenimiento para sistemas financieros",
  "Servicios de transferencia internacional de fondos",
  "Servicios de transporte internacional de carga valiosa",
  "Servicios de transporte y custodia de valores y dinero en efectivo",
  "Servicios fiduciarios y de trust",
  "Servicios legales para creación de estructuras corporativas complejas",
  "Servidores públicos",
  "Silvicultura, extracción, producción, distribución y venta",
  "Sub-contratistas",
  "Tabaco, sea la elaboración, distribución o venta de estos productos",
  "Talleres de reparación de todo tipo de equipo rodante, marítimo o aéreo",
  "Tecnología, producción, creación de equipos y de software",
  "Textiles, prendas, accesorios (bisutería) fabricación, distribución o venta",
  "Transporte de carga terreste, aéreo o marítimo",
  "Transporte de fondos y/o valores",
  "Transporte de pasajeros,terrestre, aéreo o marítimo",
  "Vendedores de automóviles y camiones usados y piezas de maquinarias",
  "Vendedores de telemercadeo",
  "Venta de antigüedades",
  "Venta de bienes raíces comerciales",
  "Venta de bienes raíces residenciales de lujo",
  "Venta de embarcaciones de lujo",
  "Venta de maquinaria pesada",
  "Venta de productos de tabaco ilegales",
  "Venta de productos farmacéuticos controlados",
  "Venta de productos para la industria petroquímica",
  "Venta de relojes de lujo",
  "Venta de software con licencias restringidas",
  "Venta y distribución de productos de salud y belleza de alto costo",
  "Zonas francas o libres, empresas ubicadas en estas zonas",
  "Otra actividad económica (no listada)",
] as const;

export type ACTIVIDADES_KYBOpcion = (typeof ACTIVIDADES_KYB_OPCIONES)[number];
