/** Generado desde Google Sheets (Profesiones). No editar a mano; ejecute `node scripts/generate-kyb-opciones.mjs`. */
export const PROFESIONES_KYB_OPCIONES = [
  "Abogados",
  "Académico (a)",
  "Actor o  Actríz",
  "Acupunturista",
  "Administrador (a)",
  "Administrador de redes",
  "Administrativo (a)",
  "Aeromozo (a)",
  "Agente aduanero",
  "Agente inmobiliario",
  "Agricultor",
  "Agrónomo",
  "Albañil",
  "Alergólogo (a)",
  "Almacenista",
  "Analista de datos",
  "Analista financiero",
  "Anestesiólogo (a)",
  "Anticuario",
  "Antropólogo (a)",
  "Arboricultor",
  "Archiviero (a)",
  "Archivista digital",
  "Arqueólogo (a)",
  "Arquitécto (a)",
  "Artesano (a)",
  "Artista",
  "Asesor Financiero",
  "Asesor legal",
  "Asistente",
  "Astrofísico",
  "Astrólogo (a)",
  "Astrónomo (a)",
  "Atleta",
  "Auditor",
  "Auditor financiero",
  "Auxiliar",
  "Azafata",
  "Bacteriólogo (a)",
  "Bailarín(a)",
  "Banquero privado",
  "Barbero",
  "Barista",
  "Barman",
  "Barrendero (a)",
  "Bedel (a) conserje",
  "Bibliotecario (a)",
  "Biofísico (a)",
  "Biógrafo (a)",
  "Biólogo (a)",
  "Biólogo marino",
  "Biotecnólogo",
  "Bloguero / Influencer",
  "Broker (corredor de bolsa)",
  "Broker de seguros",
  "Caddie (asistente de golf)",
  "Cajero (a)",
  "Cajero automático (técnico)",
  "Cajero de banco",
  "Camarero (a)",
  "Camionero de transporte de valores",
  "Cantante",
  "Cardiólogo (a)",
  "Carnicero",
  "Carpintero (a)",
  "Cartero (a)",
  "Cartógrafo (a)",
  "Cartonero (reciclador)",
  "Ceramista",
  "Cerrajero (a)",
  "Chef",
  "Chef pastelero",
  "Chofer",
  "Cirujano",
  "Coach de vida",
  "Cobrador (a)",
  "Comerciante",
  "Comerciante de arte",
  "Comerciante de bienes raíces",
  "Comerciante de metales preciosos",
  "Comerciante de vehículos de lujo",
  "Community manager",
  "Conductor (a)",
  "Constructor obrero",
  "Consultor de negocios",
  "Consultor fiscal",
  "Contador (a)",
  "Contador público",
  "Contratista constructor",
  "Contratista de obras públicas",
  "Controlador aéreo",
  "Coordinador de fondos de inversión",
  "Corredor de bienes raíces",
  "Corredor de bienes raíces de lujo",
  "Corredor de bolsa",
  "Cosmetólogo",
  "Criptomonedas trader",
  "Decorador(a) de interiores",
  "Deportista profesional",
  "Dermatólogo (a)",
  "Desarrollador de software",
  "Desempleado y/o sin profesión",
  "Dibujante",
  "Dibujante técnico",
  "Dietista",
  "Director (a)",
  "Diseñador de moda",
  "Diseñador gráfico",
  "Diseñador industrial",
  "Docente",
  "Doctor",
  "Dueño de casas de cambio",
  "Dueño de casas de empeño",
  "Dueño de casinos",
  "Dueño de clubes nocturnos",
  "Dueño de empresas offshore",
  "Dueño de galerías de arte",
  "Dueño de joyerías",
  "Dueño de negocios de importación/exportación",
  "Dueño de restaurantes exclusivos",
  "Dueño de talleres mecánicos con alto flujo de efectivo",
  "Ecólogo",
  "Economísta",
  "Editor de video",
  "Educador (a)",
  "Ejecutivo bancario de alto nivel",
  "Ejecutivo de fondos mutuos",
  "Electricista",
  "Electricista industrial",
  "Ematólogo (a)",
  "Embajador(a)",
  "Emprendedor de fintech",
  "Endocrinólogo (a)",
  "Enfermero (a)",
  "Epatólogo (a)",
  "Epidemiólogo (a)",
  "Especialista en comercio exterior",
  "Especialista en compliance",
  "Especialista en evasión fiscal",
  "Especialista en fraude financiero",
  "Especialista en lavado de dinero",
  "Especialista en mercados de capitales",
  "Especialista en recursos humanos",
  "Estadísta",
  "Estilista",
  "Estudiante",
  "Farmacéutico (a)",
  "Filósofo (a)",
  "Fiscal",
  "Físico",
  "Fisiólogo",
  "Fisioterapéuta",
  "Forense",
  "Fotógrafo",
  "Fotógrafo de moda",
  "Frutero",
  "Geólogo (a)",
  "Geoquímico",
  "Gerente",
  "Gerente de banco privado",
  "Gerente de casa de cambio",
  "Gerente de operaciones financieras",
  "Gerente de plataforma de pagos digitales",
  "Gerente de riesgo financiero",
  "Geriatra",
  "Gestor cultural",
  "Gestor de fondos de inversión",
  "Gestor de patrimonio",
  "Guardabosques",
  "Guía turístico",
  "Hacker ético",
  "Hidrógrafo (a)",
  "Higienista",
  "Historiador (a)",
  "Historiador del arte",
  "Ilustrador(a)",
  "Informático",
  "Ingeniero (a)",
  "Ingeniero ambiental",
  "Ingeniero civil",
  "Ingeniero electrónico",
  "Ingeniero en sistemas",
  "Ingeniero mecánico",
  "Ingeniero químico",
  "Intérprete",
  "Inversionista en bienes raíces",
  "Inversionista en criptomonedas",
  "Investigador",
  "Investigador científico",
  "Investigador de fraudes financieros",
  "Jardinero",
  "Jefe de cocina",
  "Jubilado (a)",
  "Juez (a)",
  "Juez en casos de lavado de dinero",
  "Kinesiólogo",
  "Lavador profesional",
  "Lavandero (a)",
  "Legal advisor en fintech",
  "Leñador",
  "Licenciado (a)",
  "Lingüista",
  "Liquidador de fondos",
  "Locutor (a)",
  "Logístico",
  "Maestro (a)",
  "Manager de casinos",
  "Maquinista",
  "Marinero",
  "Matemático (a)",
  "Mecánico",
  "Mediador(a)",
  "Mensajero (a)",
  "Mercader de oro y piedras preciosas",
  "Mesero (a)",
  "Microbiólogo",
  "Militar",
  "Modelador 3D",
  "Músico",
  "Neurocirujano (a)",
  "Neurólogo (a)",
  "Niñera",
  "Nutricionista deportivo",
  "Nutrólogo (a)",
  "Oceanógrafo (a)",
  "Oceanógrafo especializado",
  "Ocupación no listada",
  "Odontólogo u Dentista",
  "Oficinista",
  "Oftalmólogo (a)",
  "Operador de casas de cambio",
  "Operador de fondos de cobertura",
  "Operador de maquinaria pesada",
  "Operador de servicios MVTS (Money Value Transfer Services)",
  "Operador de sistemas de pago",
  "Operador de transferencias internacionales",
  "Operador en bolsa",
  "Operador en cambio de divisas",
  "Operador en cuentas numeradas",
  "Operador en mercados OTC",
  "Operador en plataformas de crowdfunding",
  "Operador en plataformas P2P",
  "Operador en transacciones de alto valor",
  "Operador en transacciones internacionales",
  "Operador financiero en banca privada",
  "Operador financiero en criptomonedas",
  "Operador financiero en fideicomisos",
  "Operador financiero en fondos fiduciarios",
  "Operador financiero en gestión de activos",
  "Operador financiero en inversiones alternativas",
  "Operador financiero en manejo de fondos extranjeros",
  "Operador financiero en paraísos fiscales",
  "Operador financiero para clientes de alto patrimonio",
  "Operador financiero para clientes no residentes",
  "Operador financiero para empresas pantalla",
  "Operador financiero para empresas shell",
  "Operador financiero para estructuras complejas",
  "Operador financiero para lavado de dinero internacional",
  "Operador financiero para manejo de activos digitales",
  "Operador financiero para mercados emergentes",
  "Operador financiero para movimientos transfronterizos",
  "Operador financiero para pagos internacionales",
  "Operador financiero para sectores de alto riesgo",
  "Operador financiero para servicios de banca corresponsal",
  "Operador financiero para servicios de custodia",
  "Operador financiero para servicios de escrow",
  "Operador financiero para servicios fiduciarios",
  "Operador financiero para servicios offshore",
  "Operador financiero para trading de activos",
  "Operador financiero para transacciones con criptomonedas",
  "Operador financiero para transacciones ilícitas",
  "Operador financiero para transferencias electrónicas",
  "Operador financiero para trusts",
  "Operador financiero para vehículos de inversión",
  "Operador inmobiliario",
  "Operador logístico de dinero en efectivo",
  "Operador mayorista de vehículos de lujo",
  "Operador minorista de metales preciosos",
  "Operador offshore",
  "Operador para lavado de activos",
  "Operario",
  "Optometrísta",
  "Optometrista clínico",
  "Organizador de eventos",
  "Orientador (a)",
  "Ortopedista",
  "Otorrinonaringologo",
  "Paleontólogo",
  "Panadero (a)",
  "Paramédico",
  "Paramédico de emergencia",
  "Partero(a)",
  "Pastelero (a)",
  "Pastor (líder religioso)",
  "Pedagogo",
  "Pediatra",
  "Pedicurista",
  "Peluquero (a)",
  "Perfumista",
  "Periodista",
  "Perito",
  "Piloto",
  "Piloto de drones",
  "Pintor de brocha gorda",
  "Podólogo",
  "Podólogo deportivo",
  "Policía",
  "Politólogo",
  "Poretero",
  "Proctólogo",
  "Profesor (a)",
  "Profesor de educación física",
  "Programador (a)",
  "Programador web",
  "Psicólogo (a)",
  "Psicopedagogo (a)",
  "Psicopedagogo escolar",
  "Psicoterapeuta",
  "Psiquiatra",
  "Publicista",
  "Publicitaria o de mercadeo",
  "Químico",
  "Quiropráctico",
  "Quiropráctico especializado",
  "Radiólogo",
  "Recepcionista",
  "Reciclaje",
  "Redactor(a) de contenido",
  "Relaciones públicas",
  "Relojero",
  "Reparador de electrodomésticos",
  "Repartidor",
  "Responsable de calidad",
  "Responsable del hogar",
  "Sacerdote",
  "Sastre",
  "Secretaria",
  "Sexólogo (a)",
  "Sismólogo",
  "Sociólogo",
  "Soldador",
  "Sommelier",
  "Taxista",
  "Técnico de sonido",
  "Técnico en electricidad",
  "Técnico en electrónica",
  "Técnico en refrigeración",
  "Técnico en seguridad industrial",
  "Técnico en sistemas computacionales",
  "Técnico en telecomunicaciones",
  "Terapeuta",
  "Traductor(a)",
  "Traumatólogo",
  "Urólogo",
  "UX/UI Designer",
  "Vendedor",
  "Vendedor ambulante",
  "Veterinario (a)",
  "Veterinario especializado en fauna silvestre",
  "Vigilante",
  "Visitador Médico",
  "Voluntario social",
  "Webmaster",
  "Youtuber",
  "Zapatero",
  "Zoologo",
  "Zoólogo marino",
  "Otra profesión u ocupación (no listada)",
] as const;

export type PROFESIONES_KYBOpcion = (typeof PROFESIONES_KYB_OPCIONES)[number];
