/**
 * Rubros MCC (Merchant Category Code) de referencia para comercios.
 * Formato: «código — descripción» (estándar ISO 18245, uso común en pagos).
 */
export const MCC_OPCIONES = [
  "0742 — Servicios veterinarios",
  "0763 — Cooperativas agrícolas",
  "0780 — Servicios de paisajismo y horticultura",
  "1520 — Contratistas residenciales y comerciales",
  "1711 — Contratistas: plomería, calefacción y aire acondicionado",
  "1731 — Contratistas eléctricos",
  "1799 — Contratistas especializados (no clasificados)",
  "2741 — Editoriales e impresiones diversas",
  "4111 — Transporte local: ferrocarril y transbordadores",
  "4112 — Transporte de pasajeros en ferrocarril",
  "4121 — Taxis y limusinas",
  "4131 — Líneas de autobús",
  "4214 — Transporte de carga por carretera",
  "4215 — Servicios de mensajería",
  "4411 — Cruceros y líneas de crucero",
  "4457 — Alquiler y leasing de embarcaciones",
  "4468 — Marinas y servicios náuticos",
  "4511 — Líneas aéreas y transporte aéreo",
  "4722 — Agencias de viajes y operadores turísticos",
  "4784 — Peajes y tarifas de carretera",
  "4812 — Equipos de telecomunicaciones y ventas",
  "4814 — Servicios de telecomunicaciones",
  "4816 — Redes de computadoras y servicios de información",
  "4899 — Cable, satélite y otros servicios de pago de TV",
  "5013 — Suministros para vehículos motorizados",
  "5021 — Mobiliario de oficina y comercial",
  "5039 — Materiales de construcción (no clasificados)",
  "5044 — Equipo fotográfico, de copiado y microfilm",
  "5045 — Computadoras, periféricos y software",
  "5046 — Equipo comercial (no clasificado)",
  "5047 — Equipo médico, oftálmico y hospitalario",
  "5051 — Centros de servicio para metales",
  "5065 — Piezas y equipo eléctrico",
  "5072 — Ferretería y suministros de plomería",
  "5074 — Equipo de calefacción y fontanería",
  "5085 — Suministros industriales (no clasificados)",
  "5094 — Joyería, relojes y platería",
  "5099 — Bienes duraderos (no clasificados)",
  "5111 — Papelería y suministros de oficina",
  "5122 — Drogas, productos farmacéuticos y cosméticos",
  "5131 — Telas, pasamanería y otros productos secos",
  "5137 — Uniformes y ropa comercial",
  "5139 — Calzado comercial",
  "5169 — Productos químicos y aliados (no clasificados)",
  "5172 — Petróleo y productos derivados del petróleo",
  "5192 — Libros, periódicos y revistas",
  "5193 — Flores, plantas y suministros de vivero",
  "5198 — Pinturas, barnices y suministros",
  "5199 — Bienes no duraderos (no clasificados)",
  "5200 — Almacenes de materiales para el hogar",
  "5211 — Madera y materiales de construcción",
  "5231 — Vidrio, pinturas y papel tapiz",
  "5251 — Ferretería",
  "5261 — Viveros y tiendas de jardinería",
  "5271 — Casas rodantes y remolques",
  "5300 — Clubes mayoristas",
  "5310 — Tiendas de descuento",
  "5311 — Grandes almacenes",
  "5331 — Tiendas de variedades",
  "5399 — Misceláneas generales",
  "5411 — Supermercados y tiendas de abarrotes",
  "5422 — Carnicerías, pescaderías y avícolas",
  "5441 — Tiendas de dulces, nueces y confitería",
  "5451 — Tiendas de productos lácteos",
  "5462 — Panaderías",
  "5499 — Misceláneas y tiendas de conveniencia",
  "5511 — Concesionarios de automóviles (nuevos y usados)",
  "5532 — Tiendas de llantas",
  "5533 — Refacciones y accesorios automotrices",
  "5541 — Estaciones de servicio",
  "5542 — Surtidores automáticos de combustible",
  "5611 — Tiendas de ropa para hombres y niños",
  "5621 — Tiendas de ropa para mujeres",
  "5631 — Tiendas de accesorios y especialidades femeninas",
  "5641 — Tiendas de ropa para niños y bebés",
  "5651 — Tiendas de ropa familiar",
  "5655 — Tiendas de ropa deportiva y de montaña",
  "5661 — Zapaterías",
  "5691 — Sastrerías y arreglos de ropa",
  "5697 — Sastres y modistas",
  "5699 — Tiendas de ropa y accesorios (misceláneas)",
  "5712 — Muebles y decoración del hogar",
  "5713 — Tapicería y alfombras",
  "5714 — Cortinas y artículos para el hogar",
  "5718 — Chimeneas y accesorios",
  "5719 — Muebles especializados",
  "5722 — Electrodomésticos",
  "5732 — Tiendas de electrónica",
  "5733 — Instrumentos musicales",
  "5734 — Software y equipo de computación",
  "5735 — Discos y tiendas de música",
  "5811 — Catering",
  "5812 — Restaurantes y establecimientos de comida",
  "5813 — Bares, discotecas y establecimientos nocturnos",
  "5814 — Comida rápida",
  "5912 — Farmacias y droguerías",
  "5921 — Licorerías y tiendas de bebidas alcohólicas empaquetadas",
  "5931 — Artículos de segunda mano y tiendas de antigüedades",
  "5932 — Tiendas de antigüedades",
  "5933 — Casas de empeño",
  "5935 — Salvamento y desguace",
  "5937 — Reproducción de antigüedades",
  "5940 — Bicicletas — venta y servicio",
  "5941 — Artículos deportivos",
  "5942 — Librerías",
  "5943 — Papelería y útiles de oficina",
  "5944 — Relojería y joyería",
  "5945 — Jugueterías y juegos",
  "5946 — Cámaras y suministros fotográficos",
  "5947 — Regalos, tarjetas y souvenirs",
  "5948 — Equipaje y artículos de cuero",
  "5949 — Suministros para costura y telas",
  "5950 — Cristalería y vajilla",
  "5960 — Marketing directo — seguros",
  "5962 — Marketing directo — viajes",
  "5963 — Venta puerta a puerta",
  "5964 — Catálogo por correo y teléfono",
  "5965 — Catálogo y venta combinada",
  "5966 — Telemarketing saliente",
  "5967 — Telemarketing entrante",
  "5968 — Suscripciones y clubes de compras",
  "5969 — Otros vendedores directos (no clasificados)",
  "5970 — Artículos para artistas y manualidades",
  "5971 — Galerías de arte y comercio de arte",
  "5972 — Sellos y monedas",
  "5973 — Artículos religiosos",
  "5975 — Audífonos y equipos de sordera",
  "5976 — Ortopedia y equipos protésicos",
  "5977 — Cosméticos",
  "5978 — Máquinas de escribir — venta y servicio",
  "5983 — Combustible — leña, carbón y petróleo licuado",
  "5992 — Floristas",
  "5993 — Tabaco y cigarros",
  "5994 — Periódicos y quioscos",
  "5995 — Tiendas de mascotas y suministros para mascotas",
  "5999 — Varios comercios minoristas especializados",
  "6010 — Instituciones financieras — desembolsos manuales",
  "6011 — Instituciones financieras — desembolsos automáticos",
  "6012 — Instituciones financieras — mercancía y servicios",
  "6051 — Monedas y divisas no fiduciarias",
  "6211 — Corredores de bolsa",
  "6300 — Seguros — primas",
  "6513 — Agentes y administradores de bienes raíces",
  "7011 — Hoteles, moteles y resorts",
  "7012 — Tiempos compartidos",
  "7032 — Campamentos deportivos y recreativos",
  "7033 — Parques de caravanas y campamentos",
  "7210 — Lavanderías y tintorerías",
  "7211 — Lavanderías — autoservicio",
  "7216 — Tintorerías",
  "7217 — Limpieza de alfombras y tapicería",
  "7221 — Estudios fotográficos",
  "7230 — Salones de belleza y peluquerías",
  "7251 — Reparación de calzado y sombreros",
  "7261 — Servicios funerarios y crematorios",
  "7273 — Servicios de citas y acompañamiento",
  "7276 — Asesoría fiscal y preparación de impuestos",
  "7277 — Servicios de consejería",
  "7278 — Clubes de compras y servicios de membresía",
  "7296 — Alquiler de ropa — disfraces y uniformes",
  "7297 — Salones de masaje",
  "7298 — Spa y salones de belleza",
  "7299 — Servicios personales diversos (no clasificados)",
  "7311 — Servicios de publicidad",
  "7333 — Fotografía comercial y arte",
  "7338 — Copias rápidas y reproducción",
  "7342 — Servicios de exterminio y desinfección",
  "7349 — Limpieza y mantenimiento",
  "7361 — Agencias de empleo",
  "7372 — Programación informática y diseño de sistemas",
  "7375 — Servicios de recuperación de información",
  "7379 — Reparación y mantenimiento de computadoras",
  "7392 — Consultoría de gestión y relaciones públicas",
  "7393 — Servicios de detective y seguridad",
  "7394 — Alquiler de equipos y herramientas",
  "7395 — Laboratorios fotográficos",
  "7399 — Servicios comerciales (no clasificados)",
  "7512 — Alquiler de automóviles",
  "7513 — Alquiler de camiones y remolques",
  "7519 — Alquiler de vehículos recreativos",
  "7523 — Estacionamientos y garajes",
  "7531 — Talleres de reparación de carrocería",
  "7534 — Recauchutado y reparación de llantas",
  "7535 — Talleres de pintura automotriz",
  "7538 — Talleres de servicio automotriz",
  "7542 — Lavado de autos",
  "7549 — Grúas y servicios de remolque",
  "7622 — Reparación de radio, TV y electrodomésticos",
  "7623 — Reparación de aire acondicionado y refrigeración",
  "7629 — Reparación de equipos eléctricos pequeños",
  "7631 — Reparación de relojes y joyería",
  "7641 — Tapicería y restauración de muebles",
  "7692 — Soldadura",
  "7699 — Talleres de reparación diversos",
  "7829 — Producción y distribución de video",
  "7832 — Cines",
  "7841 — Alquiler de cintas de video",
  "7911 — Salas de baile, estudios y escuelas de danza",
  "7922 — Productores teatrales y agencias de boletos",
  "7929 — Bandas, orquestas y artistas",
  "7932 — Establecimientos de billar y pool",
  "7933 — Boleras",
  "7941 — Clubes deportivos y campos profesionales",
  "7991 — Atracciones y exposiciones turísticas",
  "7992 — Campos de golf públicos",
  "7993 — Videojuegos y entretenimiento",
  "7994 — Videojuegos y establecimientos de juegos",
  "7995 — Apuestas, lotería y juegos de azar",
  "7996 — Parques de diversiones y circos",
  "7997 — Clubes y centros de recreación",
  "7998 — Acuarios y parques marinos",
  "7999 — Recreación y entretenimiento (no clasificados)",
  "8011 — Médicos (no clasificados)",
  "8021 — Dentistas y ortodoncistas",
  "8031 — Osteópatas",
  "8041 — Quiroprácticos",
  "8042 — Optometristas y oftalmólogos",
  "8043 — Ópticas y lentes de contacto",
  "8049 — Podólogos",
  "8050 — Enfermería y cuidado personal",
  "8062 — Hospitales",
  "8071 — Laboratorios médicos y dentales",
  "8099 — Servicios médicos (no clasificados)",
  "8111 — Servicios legales y abogados",
  "8211 — Escuelas primarias y secundarias",
  "8220 — Colegios, universidades y escuelas profesionales",
  "8241 — Escuelas por correspondencia",
  "8244 — Escuelas de negocios y secretariado",
  "8249 — Escuelas vocacionales y de oficios",
  "8299 — Escuelas y servicios educativos",
  "8351 — Servicios de cuidado infantil",
  "8398 — Organizaciones benéficas y de servicio social",
  "8641 — Asociaciones cívicas y sociales",
  "8651 — Organizaciones políticas",
  "8661 — Organizaciones religiosas",
  "8675 — Asociaciones de automóviles",
  "8699 — Organizaciones de membresía (no clasificadas)",
  "8734 — Laboratorios de pruebas (no médicos)",
  "8911 — Servicios de arquitectura e ingeniería",
  "8931 — Servicios de contabilidad, auditoría y teneduría",
  "8999 — Servicios profesionales (no clasificados)",
  "9399 — Servicios gubernamentales (no clasificados)",
  "9999 — Comercio no clasificado",
] as const;

export type MccOpcion = (typeof MCC_OPCIONES)[number];
