/**
 * Tipos de negocio de referencia (solo nombre visible al usuario).
 * El código MCC se usa solo en sistemas internos, no en el formulario.
 */
export const MCC_OPCIONES = [
  "Servicios veterinarios",
  "Cooperativas agrícolas",
  "Servicios de paisajismo y horticultura",
  "Contratistas residenciales y comerciales",
  "Contratistas: plomería, calefacción y aire acondicionado",
  "Contratistas eléctricos",
  "Contratistas especializados (no clasificados)",
  "Editoriales e impresiones diversas",
  "Transporte local: ferrocarril y transbordadores",
  "Transporte de pasajeros en ferrocarril",
  "Taxis y limusinas",
  "Líneas de autobús",
  "Transporte de carga por carretera",
  "Servicios de mensajería",
  "Cruceros y líneas de crucero",
  "Alquiler y leasing de embarcaciones",
  "Marinas y servicios náuticos",
  "Líneas aéreas y transporte aéreo",
  "Agencias de viajes y operadores turísticos",
  "Peajes y tarifas de carretera",
  "Equipos de telecomunicaciones y ventas",
  "Servicios de telecomunicaciones",
  "Redes de computadoras y servicios de información",
  "Cable, satélite y otros servicios de pago de TV",
  "Suministros para vehículos motorizados",
  "Mobiliario de oficina y comercial",
  "Materiales de construcción (no clasificados)",
  "Equipo fotográfico, de copiado y microfilm",
  "Computadoras, periféricos y software",
  "Equipo comercial (no clasificado)",
  "Equipo médico, oftálmico y hospitalario",
  "Centros de servicio para metales",
  "Piezas y equipo eléctrico",
  "Ferretería y suministros de plomería",
  "Equipo de calefacción y fontanería",
  "Suministros industriales (no clasificados)",
  "Joyería, relojes y platería",
  "Bienes duraderos (no clasificados)",
  "Papelería y suministros de oficina",
  "Drogas, productos farmacéuticos y cosméticos",
  "Telas, pasamanería y otros productos secos",
  "Uniformes y ropa comercial",
  "Calzado comercial",
  "Productos químicos y aliados (no clasificados)",
  "Petróleo y productos derivados del petróleo",
  "Libros, periódicos y revistas",
  "Flores, plantas y suministros de vivero",
  "Pinturas, barnices y suministros",
  "Bienes no duraderos (no clasificados)",
  "Almacenes de materiales para el hogar",
  "Madera y materiales de construcción",
  "Vidrio, pinturas y papel tapiz",
  "Ferretería",
  "Viveros y tiendas de jardinería",
  "Casas rodantes y remolques",
  "Clubes mayoristas",
  "Tiendas de descuento",
  "Grandes almacenes",
  "Tiendas de variedades",
  "Misceláneas generales",
  "Supermercados y tiendas de abarrotes",
  "Carnicerías, pescaderías y avícolas",
  "Tiendas de dulces, nueces y confitería",
  "Tiendas de productos lácteos",
  "Panaderías",
  "Misceláneas y tiendas de conveniencia",
  "Concesionarios de automóviles (nuevos y usados)",
  "Tiendas de llantas",
  "Refacciones y accesorios automotrices",
  "Estaciones de servicio",
  "Surtidores automáticos de combustible",
  "Tiendas de ropa para hombres y niños",
  "Tiendas de ropa para mujeres",
  "Tiendas de accesorios y especialidades femeninas",
  "Tiendas de ropa para niños y bebés",
  "Tiendas de ropa familiar",
  "Tiendas de ropa deportiva y de montaña",
  "Zapaterías",
  "Sastrerías y arreglos de ropa",
  "Sastres y modistas",
  "Tiendas de ropa y accesorios (misceláneas)",
  "Muebles y decoración del hogar",
  "Tapicería y alfombras",
  "Cortinas y artículos para el hogar",
  "Chimeneas y accesorios",
  "Muebles especializados",
  "Electrodomésticos",
  "Tiendas de electrónica",
  "Instrumentos musicales",
  "Software y equipo de computación",
  "Discos y tiendas de música",
  "Catering",
  "Restaurantes y establecimientos de comida",
  "Bares, discotecas y establecimientos nocturnos",
  "Comida rápida",
  "Farmacias y droguerías",
  "Licorerías y tiendas de bebidas alcohólicas empaquetadas",
  "Artículos de segunda mano y tiendas de antigüedades",
  "Tiendas de antigüedades",
  "Casas de empeño",
  "Salvamento y desguace",
  "Reproducción de antigüedades",
  "Bicicletas — venta y servicio",
  "Artículos deportivos",
  "Librerías",
  "Papelería y útiles de oficina",
  "Relojería y joyería",
  "Jugueterías y juegos",
  "Cámaras y suministros fotográficos",
  "Regalos, tarjetas y souvenirs",
  "Equipaje y artículos de cuero",
  "Suministros para costura y telas",
  "Cristalería y vajilla",
  "Marketing directo — seguros",
  "Marketing directo — viajes",
  "Venta puerta a puerta",
  "Catálogo por correo y teléfono",
  "Catálogo y venta combinada",
  "Telemarketing saliente",
  "Telemarketing entrante",
  "Suscripciones y clubes de compras",
  "Otros vendedores directos (no clasificados)",
  "Artículos para artistas y manualidades",
  "Galerías de arte y comercio de arte",
  "Sellos y monedas",
  "Artículos religiosos",
  "Audífonos y equipos de sordera",
  "Ortopedia y equipos protésicos",
  "Cosméticos",
  "Máquinas de escribir — venta y servicio",
  "Combustible — leña, carbón y petróleo licuado",
  "Floristas",
  "Tabaco y cigarros",
  "Periódicos y quioscos",
  "Tiendas de mascotas y suministros para mascotas",
  "Varios comercios minoristas especializados",
  "Instituciones financieras — desembolsos manuales",
  "Instituciones financieras — desembolsos automáticos",
  "Instituciones financieras — mercancía y servicios",
  "Monedas y divisas no fiduciarias",
  "Corredores de bolsa",
  "Seguros — primas",
  "Agentes y administradores de bienes raíces",
  "Hoteles, moteles y resorts",
  "Tiempos compartidos",
  "Campamentos deportivos y recreativos",
  "Parques de caravanas y campamentos",
  "Lavanderías y tintorerías",
  "Lavanderías — autoservicio",
  "Tintorerías",
  "Limpieza de alfombras y tapicería",
  "Estudios fotográficos",
  "Salones de belleza y peluquerías",
  "Reparación de calzado y sombreros",
  "Servicios funerarios y crematorios",
  "Servicios de citas y acompañamiento",
  "Asesoría fiscal y preparación de impuestos",
  "Servicios de consejería",
  "Clubes de compras y servicios de membresía",
  "Alquiler de ropa — disfraces y uniformes",
  "Salones de masaje",
  "Spa y salones de belleza",
  "Servicios personales diversos (no clasificados)",
  "Servicios de publicidad",
  "Fotografía comercial y arte",
  "Copias rápidas y reproducción",
  "Servicios de exterminio y desinfección",
  "Limpieza y mantenimiento",
  "Agencias de empleo",
  "Programación informática y diseño de sistemas",
  "Servicios de recuperación de información",
  "Reparación y mantenimiento de computadoras",
  "Consultoría de gestión y relaciones públicas",
  "Servicios de detective y seguridad",
  "Alquiler de equipos y herramientas",
  "Laboratorios fotográficos",
  "Servicios comerciales (no clasificados)",
  "Alquiler de automóviles",
  "Alquiler de camiones y remolques",
  "Alquiler de vehículos recreativos",
  "Estacionamientos y garajes",
  "Talleres de reparación de carrocería",
  "Recauchutado y reparación de llantas",
  "Talleres de pintura automotriz",
  "Talleres de servicio automotriz",
  "Lavado de autos",
  "Grúas y servicios de remolque",
  "Reparación de radio, TV y electrodomésticos",
  "Reparación de aire acondicionado y refrigeración",
  "Reparación de equipos eléctricos pequeños",
  "Reparación de relojes y joyería",
  "Tapicería y restauración de muebles",
  "Soldadura",
  "Talleres de reparación diversos",
  "Producción y distribución de video",
  "Cines",
  "Alquiler de cintas de video",
  "Salas de baile, estudios y escuelas de danza",
  "Productores teatrales y agencias de boletos",
  "Bandas, orquestas y artistas",
  "Establecimientos de billar y pool",
  "Boleras",
  "Clubes deportivos y campos profesionales",
  "Atracciones y exposiciones turísticas",
  "Campos de golf públicos",
  "Videojuegos y entretenimiento",
  "Videojuegos y establecimientos de juegos",
  "Apuestas, lotería y juegos de azar",
  "Parques de diversiones y circos",
  "Clubes y centros de recreación",
  "Acuarios y parques marinos",
  "Recreación y entretenimiento (no clasificados)",
  "Médicos (no clasificados)",
  "Dentistas y ortodoncistas",
  "Osteópatas",
  "Quiroprácticos",
  "Optometristas y oftalmólogos",
  "Ópticas y lentes de contacto",
  "Podólogos",
  "Enfermería y cuidado personal",
  "Hospitales",
  "Laboratorios médicos y dentales",
  "Servicios médicos (no clasificados)",
  "Servicios legales y abogados",
  "Escuelas primarias y secundarias",
  "Colegios, universidades y escuelas profesionales",
  "Escuelas por correspondencia",
  "Escuelas de negocios y secretariado",
  "Escuelas vocacionales y de oficios",
  "Escuelas y servicios educativos",
  "Servicios de cuidado infantil",
  "Organizaciones benéficas y de servicio social",
  "Asociaciones cívicas y sociales",
  "Organizaciones políticas",
  "Organizaciones religiosas",
  "Asociaciones de automóviles",
  "Organizaciones de membresía (no clasificadas)",
  "Laboratorios de pruebas (no médicos)",
  "Servicios de arquitectura e ingeniería",
  "Servicios de contabilidad, auditoría y teneduría",
  "Servicios profesionales (no clasificados)",
  "Servicios gubernamentales (no clasificados)",
  "Comercio no clasificado",
] as const;

export type MccOpcion = (typeof MCC_OPCIONES)[number];
