/**
 * Tipos de negocio de referencia (código interno entre paréntesis).
 * Formato: «nombre (código)».
 */
export const MCC_OPCIONES = [
  "Servicios veterinarios (0742)",
  "Cooperativas agrícolas (0763)",
  "Servicios de paisajismo y horticultura (0780)",
  "Contratistas residenciales y comerciales (1520)",
  "Contratistas: plomería, calefacción y aire acondicionado (1711)",
  "Contratistas eléctricos (1731)",
  "Contratistas especializados (no clasificados) (1799)",
  "Editoriales e impresiones diversas (2741)",
  "Transporte local: ferrocarril y transbordadores (4111)",
  "Transporte de pasajeros en ferrocarril (4112)",
  "Taxis y limusinas (4121)",
  "Líneas de autobús (4131)",
  "Transporte de carga por carretera (4214)",
  "Servicios de mensajería (4215)",
  "Cruceros y líneas de crucero (4411)",
  "Alquiler y leasing de embarcaciones (4457)",
  "Marinas y servicios náuticos (4468)",
  "Líneas aéreas y transporte aéreo (4511)",
  "Agencias de viajes y operadores turísticos (4722)",
  "Peajes y tarifas de carretera (4784)",
  "Equipos de telecomunicaciones y ventas (4812)",
  "Servicios de telecomunicaciones (4814)",
  "Redes de computadoras y servicios de información (4816)",
  "Cable, satélite y otros servicios de pago de TV (4899)",
  "Suministros para vehículos motorizados (5013)",
  "Mobiliario de oficina y comercial (5021)",
  "Materiales de construcción (no clasificados) (5039)",
  "Equipo fotográfico, de copiado y microfilm (5044)",
  "Computadoras, periféricos y software (5045)",
  "Equipo comercial (no clasificado) (5046)",
  "Equipo médico, oftálmico y hospitalario (5047)",
  "Centros de servicio para metales (5051)",
  "Piezas y equipo eléctrico (5065)",
  "Ferretería y suministros de plomería (5072)",
  "Equipo de calefacción y fontanería (5074)",
  "Suministros industriales (no clasificados) (5085)",
  "Joyería, relojes y platería (5094)",
  "Bienes duraderos (no clasificados) (5099)",
  "Papelería y suministros de oficina (5111)",
  "Drogas, productos farmacéuticos y cosméticos (5122)",
  "Telas, pasamanería y otros productos secos (5131)",
  "Uniformes y ropa comercial (5137)",
  "Calzado comercial (5139)",
  "Productos químicos y aliados (no clasificados) (5169)",
  "Petróleo y productos derivados del petróleo (5172)",
  "Libros, periódicos y revistas (5192)",
  "Flores, plantas y suministros de vivero (5193)",
  "Pinturas, barnices y suministros (5198)",
  "Bienes no duraderos (no clasificados) (5199)",
  "Almacenes de materiales para el hogar (5200)",
  "Madera y materiales de construcción (5211)",
  "Vidrio, pinturas y papel tapiz (5231)",
  "Ferretería (5251)",
  "Viveros y tiendas de jardinería (5261)",
  "Casas rodantes y remolques (5271)",
  "Clubes mayoristas (5300)",
  "Tiendas de descuento (5310)",
  "Grandes almacenes (5311)",
  "Tiendas de variedades (5331)",
  "Misceláneas generales (5399)",
  "Supermercados y tiendas de abarrotes (5411)",
  "Carnicerías, pescaderías y avícolas (5422)",
  "Tiendas de dulces, nueces y confitería (5441)",
  "Tiendas de productos lácteos (5451)",
  "Panaderías (5462)",
  "Misceláneas y tiendas de conveniencia (5499)",
  "Concesionarios de automóviles (nuevos y usados) (5511)",
  "Tiendas de llantas (5532)",
  "Refacciones y accesorios automotrices (5533)",
  "Estaciones de servicio (5541)",
  "Surtidores automáticos de combustible (5542)",
  "Tiendas de ropa para hombres y niños (5611)",
  "Tiendas de ropa para mujeres (5621)",
  "Tiendas de accesorios y especialidades femeninas (5631)",
  "Tiendas de ropa para niños y bebés (5641)",
  "Tiendas de ropa familiar (5651)",
  "Tiendas de ropa deportiva y de montaña (5655)",
  "Zapaterías (5661)",
  "Sastrerías y arreglos de ropa (5691)",
  "Sastres y modistas (5697)",
  "Tiendas de ropa y accesorios (misceláneas) (5699)",
  "Muebles y decoración del hogar (5712)",
  "Tapicería y alfombras (5713)",
  "Cortinas y artículos para el hogar (5714)",
  "Chimeneas y accesorios (5718)",
  "Muebles especializados (5719)",
  "Electrodomésticos (5722)",
  "Tiendas de electrónica (5732)",
  "Instrumentos musicales (5733)",
  "Software y equipo de computación (5734)",
  "Discos y tiendas de música (5735)",
  "Catering (5811)",
  "Restaurantes y establecimientos de comida (5812)",
  "Bares, discotecas y establecimientos nocturnos (5813)",
  "Comida rápida (5814)",
  "Farmacias y droguerías (5912)",
  "Licorerías y tiendas de bebidas alcohólicas empaquetadas (5921)",
  "Artículos de segunda mano y tiendas de antigüedades (5931)",
  "Tiendas de antigüedades (5932)",
  "Casas de empeño (5933)",
  "Salvamento y desguace (5935)",
  "Reproducción de antigüedades (5937)",
  "Bicicletas — venta y servicio (5940)",
  "Artículos deportivos (5941)",
  "Librerías (5942)",
  "Papelería y útiles de oficina (5943)",
  "Relojería y joyería (5944)",
  "Jugueterías y juegos (5945)",
  "Cámaras y suministros fotográficos (5946)",
  "Regalos, tarjetas y souvenirs (5947)",
  "Equipaje y artículos de cuero (5948)",
  "Suministros para costura y telas (5949)",
  "Cristalería y vajilla (5950)",
  "Marketing directo — seguros (5960)",
  "Marketing directo — viajes (5962)",
  "Venta puerta a puerta (5963)",
  "Catálogo por correo y teléfono (5964)",
  "Catálogo y venta combinada (5965)",
  "Telemarketing saliente (5966)",
  "Telemarketing entrante (5967)",
  "Suscripciones y clubes de compras (5968)",
  "Otros vendedores directos (no clasificados) (5969)",
  "Artículos para artistas y manualidades (5970)",
  "Galerías de arte y comercio de arte (5971)",
  "Sellos y monedas (5972)",
  "Artículos religiosos (5973)",
  "Audífonos y equipos de sordera (5975)",
  "Ortopedia y equipos protésicos (5976)",
  "Cosméticos (5977)",
  "Máquinas de escribir — venta y servicio (5978)",
  "Combustible — leña, carbón y petróleo licuado (5983)",
  "Floristas (5992)",
  "Tabaco y cigarros (5993)",
  "Periódicos y quioscos (5994)",
  "Tiendas de mascotas y suministros para mascotas (5995)",
  "Varios comercios minoristas especializados (5999)",
  "Instituciones financieras — desembolsos manuales (6010)",
  "Instituciones financieras — desembolsos automáticos (6011)",
  "Instituciones financieras — mercancía y servicios (6012)",
  "Monedas y divisas no fiduciarias (6051)",
  "Corredores de bolsa (6211)",
  "Seguros — primas (6300)",
  "Agentes y administradores de bienes raíces (6513)",
  "Hoteles, moteles y resorts (7011)",
  "Tiempos compartidos (7012)",
  "Campamentos deportivos y recreativos (7032)",
  "Parques de caravanas y campamentos (7033)",
  "Lavanderías y tintorerías (7210)",
  "Lavanderías — autoservicio (7211)",
  "Tintorerías (7216)",
  "Limpieza de alfombras y tapicería (7217)",
  "Estudios fotográficos (7221)",
  "Salones de belleza y peluquerías (7230)",
  "Reparación de calzado y sombreros (7251)",
  "Servicios funerarios y crematorios (7261)",
  "Servicios de citas y acompañamiento (7273)",
  "Asesoría fiscal y preparación de impuestos (7276)",
  "Servicios de consejería (7277)",
  "Clubes de compras y servicios de membresía (7278)",
  "Alquiler de ropa — disfraces y uniformes (7296)",
  "Salones de masaje (7297)",
  "Spa y salones de belleza (7298)",
  "Servicios personales diversos (no clasificados) (7299)",
  "Servicios de publicidad (7311)",
  "Fotografía comercial y arte (7333)",
  "Copias rápidas y reproducción (7338)",
  "Servicios de exterminio y desinfección (7342)",
  "Limpieza y mantenimiento (7349)",
  "Agencias de empleo (7361)",
  "Programación informática y diseño de sistemas (7372)",
  "Servicios de recuperación de información (7375)",
  "Reparación y mantenimiento de computadoras (7379)",
  "Consultoría de gestión y relaciones públicas (7392)",
  "Servicios de detective y seguridad (7393)",
  "Alquiler de equipos y herramientas (7394)",
  "Laboratorios fotográficos (7395)",
  "Servicios comerciales (no clasificados) (7399)",
  "Alquiler de automóviles (7512)",
  "Alquiler de camiones y remolques (7513)",
  "Alquiler de vehículos recreativos (7519)",
  "Estacionamientos y garajes (7523)",
  "Talleres de reparación de carrocería (7531)",
  "Recauchutado y reparación de llantas (7534)",
  "Talleres de pintura automotriz (7535)",
  "Talleres de servicio automotriz (7538)",
  "Lavado de autos (7542)",
  "Grúas y servicios de remolque (7549)",
  "Reparación de radio, TV y electrodomésticos (7622)",
  "Reparación de aire acondicionado y refrigeración (7623)",
  "Reparación de equipos eléctricos pequeños (7629)",
  "Reparación de relojes y joyería (7631)",
  "Tapicería y restauración de muebles (7641)",
  "Soldadura (7692)",
  "Talleres de reparación diversos (7699)",
  "Producción y distribución de video (7829)",
  "Cines (7832)",
  "Alquiler de cintas de video (7841)",
  "Salas de baile, estudios y escuelas de danza (7911)",
  "Productores teatrales y agencias de boletos (7922)",
  "Bandas, orquestas y artistas (7929)",
  "Establecimientos de billar y pool (7932)",
  "Boleras (7933)",
  "Clubes deportivos y campos profesionales (7941)",
  "Atracciones y exposiciones turísticas (7991)",
  "Campos de golf públicos (7992)",
  "Videojuegos y entretenimiento (7993)",
  "Videojuegos y establecimientos de juegos (7994)",
  "Apuestas, lotería y juegos de azar (7995)",
  "Parques de diversiones y circos (7996)",
  "Clubes y centros de recreación (7997)",
  "Acuarios y parques marinos (7998)",
  "Recreación y entretenimiento (no clasificados) (7999)",
  "Médicos (no clasificados) (8011)",
  "Dentistas y ortodoncistas (8021)",
  "Osteópatas (8031)",
  "Quiroprácticos (8041)",
  "Optometristas y oftalmólogos (8042)",
  "Ópticas y lentes de contacto (8043)",
  "Podólogos (8049)",
  "Enfermería y cuidado personal (8050)",
  "Hospitales (8062)",
  "Laboratorios médicos y dentales (8071)",
  "Servicios médicos (no clasificados) (8099)",
  "Servicios legales y abogados (8111)",
  "Escuelas primarias y secundarias (8211)",
  "Colegios, universidades y escuelas profesionales (8220)",
  "Escuelas por correspondencia (8241)",
  "Escuelas de negocios y secretariado (8244)",
  "Escuelas vocacionales y de oficios (8249)",
  "Escuelas y servicios educativos (8299)",
  "Servicios de cuidado infantil (8351)",
  "Organizaciones benéficas y de servicio social (8398)",
  "Asociaciones cívicas y sociales (8641)",
  "Organizaciones políticas (8651)",
  "Organizaciones religiosas (8661)",
  "Asociaciones de automóviles (8675)",
  "Organizaciones de membresía (no clasificadas) (8699)",
  "Laboratorios de pruebas (no médicos) (8734)",
  "Servicios de arquitectura e ingeniería (8911)",
  "Servicios de contabilidad, auditoría y teneduría (8931)",
  "Servicios profesionales (no clasificados) (8999)",
  "Servicios gubernamentales (no clasificados) (9399)",
  "Comercio no clasificado (9999)",
] as const;

export type MccOpcion = (typeof MCC_OPCIONES)[number];
